package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SIGNAL extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SIGNAL() {
    super(0x7d30aba23d1348acL, 0xb67656f691260962L, 0x4d1785670cfc7e42L, "SIGNAL", "r:fc2ace7f-3179-4cd5-b9f8-784768ae9487(ArduinoML.structure)/5555055343030795842");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_HIGH_0 = new EnumerationDescriptor.MemberDescriptor("HIGH", "on", 0x4d1785670cfc7e43L, "r:fc2ace7f-3179-4cd5-b9f8-784768ae9487(ArduinoML.structure)/5555055343030795843");
  private final EnumerationDescriptor.MemberDescriptor myMember_LOW_0 = new EnumerationDescriptor.MemberDescriptor("LOW", "off", 0x4d1785670cfc7e68L, "r:fc2ace7f-3179-4cd5-b9f8-784768ae9487(ArduinoML.structure)/5555055343030795880");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7d30aba23d1348acL, 0xb67656f691260962L, 0x4d1785670cfc7e42L, 0x4d1785670cfc7e43L, 0x4d1785670cfc7e68L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_HIGH_0, myMember_LOW_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_HIGH_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "HIGH":
        return myMember_HIGH_0;
      case "LOW":
        return myMember_LOW_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
