package ArduinoML.sandbox;

/*Generated by MPS */


public class map_App {

  public static void main(String[] args) {
    System.out.println("// code generated");

    System.out.println("void setup() {");
    System.out.println("    pinMode(" + 9 + ", OUTPUT);");
    System.out.println("    pinMode(" + 12 + ", INPUT);");
    System.out.println("}");

    System.out.println("\n// Behavioral concepts");
    System.out.println("long time = 0; long debounce = 200;\n");
    System.out.println("void state_" + "on" + "() {");
    System.out.println("    digitalWrite(" + 9 + "," + "HIGH" + ");");
    System.out.println("}\n");
    System.out.println("void state_" + "off" + "() {");
    System.out.println("    if(digitalRead(" + 0 + ") " + "AND" + " " + "HIGH" + ") {");
    System.out.println("        ");
    System.out.println("    }");
    System.out.println("}\n");
    System.out.println("void loop() { state_" + "on" + "(); } // entering init state\n");
  }
}
